# For information on these settings, see:
#    https://www.appveyor.com/docs/build-configuration/
#    https://www.appveyor.com/docs/appveyor-yml/
#
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# The following is supported by default. See:
#   https://www.appveyor.com/docs/how-to/filtering-commits/
#
#skip_commits:
#  message: /\[appveyor skip\]/|/\[skip appveyor\]/

#image: Visual Studio 2017

branches:
  only:
    - master

#platform:
#  - Win32
#  - x64

#configuration:
#  - Debug
#  - Release

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017 Win64"
      CONFIG: Debug
    - GENERATOR: "Visual Studio 15 2017 Win64"
      CONFIG: Release
    - GENERATOR: "Visual Studio 15 2017"
      CONFIG: Debug
    - GENERATOR: "Visual Studio 15 2017"
      CONFIG: Release

install:
  - ps: choco install doxygen.portable
  - ps: choco install graphviz

#test_script:
#- ps: |
#    If ($env:PLATFORM -Match "Win32") {
#      $env:PLAYRHO_EXE="x32"
#    }
#    If ($env:PLATFORM -Match "x64") {
#      $env:PLAYRHO_EXE="x64"
#    }
#    Start-Process -FilePath "\projects\playrho\Build\vs2017\bin\$env:PLAYRHO_EXE\$env:CONFIGURATION\HelloWorld.exe" -RedirectStandardOutput "Hello.txt" -Wait -NoNewWindow

build_script:
  - cd c:\projects\PlayRho\Build
  - echo Running cmake...
  - cmake -G "%GENERATOR%" -DPLAYRHO_BUILD_HELLOWORLD=ON ..
  - cmake --build . --config "%CONFIG%"

#build:
#  project: Build/vs2017/PlayRho.sln
#  verbosity: normal

after_build:
  - set PATH=c:\Program Files (x86)\graphviz2.38\bin;%PATH%
  - cd Documentation
  - doxygen Doxyfile
  - cd ..

artifacts:
  - path: Documentation\API
    name: API Documentation
  - path: Build\vs2017\bin
    name: Binary Executables
