# For information on these settings, see:
#    https://www.appveyor.com/docs/build-configuration/
#    https://www.appveyor.com/docs/appveyor-yml/
#
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# The following is supported by default. See:
#   https://www.appveyor.com/docs/how-to/filtering-commits/
#
#skip_commits:
#  message: /\[appveyor skip\]/|/\[skip appveyor\]/

image: Visual Studio 2017

build:
  project: Build/vs2017/PlayRho.sln
  verbosity: normal

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

install:
  - ps: choco install doxygen.portable

test_script:
- ps: |
    If ($env:PLATFORM -Match "Win32") {
      $env:PLAYRHO_EXE="x32"
    }
    If ($env:PLATFORM -Match "x64") {
      $env:PLAYRHO_EXE="x64"
    }
    Start-Process -FilePath "\projects\playrho\Build\vs2017\bin\$env:PLAYRHO_EXE\$env:CONFIGURATION\HelloWorld.exe" -RedirectStandardOutput "Hello.txt" -Wait -NoNewWindow

after_build:
  - cd Documentation
  - doxygen Doxyfile
  - cd ..
